### ISSUE TITLE
Please add feature to specify a profile transform override

### ISSUE THREAD

**Issue by kevintechie** [node-saml/passport-saml#109]
When using login systems that support multiple authentication providers, the user profile returned by the passport authenticate method is usually normalized to the [Portable Contacts](http://portablecontacts.net/draft-spec.html) spec. The profile returned by passport-saml does not conform to that spec.

It would be helpful if an overridable transform method was added to the passport-saml. The authenticate method would call the transform just before returning the profile. Currently, I have to override the the entire authenticate method to transform the profile.

**Comment by ploer** [comment]
What sorts of fields are you interested in pulling out here -- just very basic things like provider, id, and email?  If so I think we could just extend the profile object returned to provide those in the portable contacts structure in addition to their current location.

Basically I'm wondering if there's something simpler than an arbitrary transform that we could do here.

**Comment by kevintechie** [comment]
For me, yes, provider, id, and email are adequate. However, I'm not sure that the attribute mapping will be the same for all saml profiles. In addition, I can foresee some people needing affiliations and other attributes.

I'm using the following map that is common for my organization:

  var profileAttrs = {
    'urn:oid:0.9.2342.19200300.100.1.1': 'netId',
    'urn:oid:2.16.840.1.113730.3.1.241': 'displayName',
    'urn:oid:1.3.6.1.4.1.5923.1.1.1.1':  'affiliation',
    'urn:oid:2.5.4.3':                   'cn',
    'urn:oid:0.9.2342.19200300.100.1.3': 'email',
    'urn:oid:2.16.840.1.113730.3.1.3':   'empNum',
    'urn:oid:1.3.6.1.4.1.5923.1.1.1.6':  'principalName',
    'urn:oid:2.5.4.42':                  'givenName',
    'urn:oid:2.5.4.18':                  'box',
    'urn:oid:2.5.4.20':                  'phone',
    'urn:oid:2.5.4.4':                   'surname',
    'urn:oid:2.5.4.12':                  'title',
    'urn:oid:1.2.840.113994.200.21':     'studentId',
    'urn:oid:1.2.840.113994.200.24':     'regId'
  };

And then I build the user for passport multi-auth:

    user.provider = strategyName;
    user.id = user.netId;
    user.emails = [
      {
        value: user.principalName
      }
    ];

I get strategyName from the Strategy instance.

However, if you provide a method:

    Strategy.prototype.userProfile = function (profile) {
      return profile;
    }

...and call it just before calling _verify:

    if (self._passReqToCallback) {
      self._verify(req, userProfile(profile), verified);
    } else {
      self._verify(userProfile(profile), verified);
    }

It's not much code for you to maintain and enables anyone that needs custom mapping to implement it themselves.

This is similar to how the [passport-oauth2](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L243) provider works.

Here it is overridden for [Google](https://github.com/jaredhanson/passport-google-oauth/blob/master/lib/passport-google-oauth/oauth2.js#L86).

**Comment by JSteunou** [comment]
+1 coming from oauth2 `userProfile` is a nice hook to build profile object.

**Comment by cjbarth** [comment]
It seems that this mapping might be deprecated based on [this](https://spaces.internet2.edu/display/InCFederation/Supported+Attribute+Summary). Is there some documentation that indicates which SAML properties should map to the Portable Contacts spec?

**Comment by cjbarth** [comment]
The user profile object is now much more robust, and includes the native XML object if needed.
