### ISSUE TITLE
Create Own Identity Provider

### ISSUE THREAD

**Issue by Rachit17** [node-saml/passport-saml#145]
Hi ,

I want to create my own idp rather than using feide openidp, and want to parse the request,create the saml response if the user is authenticated and send it back to service provide. Could you please help me with the steps/code samples?

**Comment by Indrani123** [comment]
For creating your own IDP you have to understand various security concepts.
for example SAML, federation, IdP and service provider concepts

steps:1st send SamlAuthnRequest to your IDP

your Idp should verify the request that it is coming from known service provider.


and your IDP generate samlResponse to for the request .

2. The passport-saml module will verify the samlResponse which will contain assertion,

and claims, once validated ,you will get your user details claims etc.


Thanks,

**Comment by Rachit17** [comment]
Thanks Indrani. But i have a doubt like i am able to send saml authn
request to my idp and able to validate user at idp from ldap as i have
integrated my ldap with idp app,but the problem is how to create a valid
saml response in xml ,how do we do in java script or is there any saml
generator tool that can do .

*Thanks & Regards*
*Rachit Kakkar*

**Comment by Indrani123** [comment]
it is complete depend upon you what language you had choose to create your IDP either java/JavaScript.

,Nodejs have some 
xml generater modules, you have to use some of those,you also have to learned some of them,check how passport-saml sends SamlRequest to its also xml right,


There is now way ,you have to learned basic SAML concepts.

Thanks,

**Comment by zccaliDev** [comment]
use express-saml2

**Comment by mans0954** [comment]
Closing as implementing an IdP is out of scope for this project.
