### ISSUE TITLE
Crash/Hang in SAML Postback parsing.

### ISSUE THREAD

**Issue by p41nfr4m3** [node-saml/passport-saml#159]
If a postback with the following invalid XML response is submitted:

`SAMLResponse=<?xml version="1.0" encoding="UTF-8"?><samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://testapp.com/ssocallback" ID="_c14111b17d31f9f1151175171514e1c1116512151918" InResponseTo="_1f1f1861d710f517f7cb" IssueInstant="2016-06-07T18:02:39.786Z" Version="2.0"></samlp:Response>%}lv0iv'/"<mt1e9
`
the xml is being parsed and then everything seems to lock up.

**Comment by markstos** [comment]
Re-open if you've got a test case to reproduce this.
