### ISSUE TITLE
saml authentication provider

### ISSUE THREAD

**Issue by peacemakr** [node-saml/passport-saml#184]
I was looking for a module to allow my nodejs app be the SAML authentication/identity provider so other apps could authenticate users through my app. 

Is this something that is possible through this module? If not, is there another module that would be of help?

**Comment by tilleps** [comment]
Try samlp from Auth0:  https://github.com/auth0/node-samlp

**Comment by mans0954** [comment]
Closing as implementing an IdP is out of scope for this project.
