### ISSUE TITLE
Access attributes from IdP?

### ISSUE THREAD

**Issue by jakobsen9** [node-saml/passport-saml#188]
Hi all,

I am using Angular 2, and would like to take usage of the attributes the IdP provides in the SAML response. Where are those attributes stored, and how can I call them in for ex. a html file? Are they stored in any global variables?

**Comment by jakobsen9** [comment]
I have tried the implementation presented in #165, but I get the error `Error: passport.initialize() middleware not in use`. I have found out that the error occours when the 2nd return argument is set in this:
`var strategy = new SamlStrategy(
  {
    callbackUrl: 'http://localhost:3000/login/callback',
    entryPoint: 'https://idp-test.feide.no/simplesaml/saml2/idp/SSOService.php',
    issuer: 'http://localhost:3000/feide/metadata',
    logoutUrl: 'https://idp-test.feide.no/simplesaml/saml2/idp/SingleLogoutService.php',
    logoutCallbackUrl: 'http://localhost:3000/logout'
  },
  function(profile, done) {
    return done(null, 
      {
          id: profile.uid,
          email: profile.mail
      });
  })`
Earlier I had only the first return argument, `return done(null)`, and that worked.

**Comment by jakobsen9** [comment]
Found out that I missed the following in the same file as above:

 

>  passport.serializeUser(function (user, done) {
>     done(null, user);
>   });
> 
>   passport.deserializeUser(function (user, done) {
>     done(null, user);
>   });
> 
> router.use(passport.initialize());

Now it's working without errors, and I have printed to see that the attributes are saved in `user`. 

But I still don't figure out how to call the arguments. I have tried `{{user.email}}` in the html file, but error says `Error: Error in ./PostsComponent class PostsComponent - inline template:12:39 caused by: undefined is not an object (evaluating 'self.context.user.email')`.

**Comment by jakobsen9** [comment]
@ploer Hi, documentation on how to access and use the attributes are really missing...

**Comment by pdspicer** [comment]
How you use the attributes after returning a value from the `verify` callback is really dependent on your passport configuration. Default behavior is that `req.user` is populated after a successful call to `passport.authenticate()`, which you can certainly then return to your front-end however you'd like.
