### ISSUE TITLE
Logout TypeError: SamlStrategy.logout is not a function

### ISSUE THREAD

**Issue by mbabar-cs** [node-saml/passport-saml#200]
Hello,
I am getting **### TypeError: SamlStrategy.logout is not a function** when I try to logout. Given below is my code

`var passport = require('passport');  //"passport": "^0.3.2",
var SamlStrategy = require('passport-saml').Strategy; //"passport-saml": "^0.15.0",

passport.use(new SamlStrategy({
    path: '/login/callback',
    entryPoint: 'https://xxxxxxxxxxxxxxxx.okta.com/app/xxxxxxxx_xxxxsamlapplication_1/xxxxxxxxxxxxxxxxxxxx/sso/saml',
    logoutUrl: 'https://xxxxxxxx.okta.com/app/xxxxxxxx_xxxxsamlapplication_1/xxxxxxxxxxxxxxxxxxxx/slo/saml',
    logoutCallbackUrl: '/logout/callback',
    issuer: 'passport-saml',
}, function(profile, done) {
    return done(null, {
        id: profile.nameID,
        sessionIndex: profile.sessionIndex,
        email: profile.Email,
        firstName: profile.FirstName,
        lastName: profile.LastName,
        city: profile.city,
        roles: profile.RoleInfo,
    });
}));
app.get('/logout', function(req, res) {
    console.log('In int----------------------------');
    //Here add the nameID and nameIDFormat to the user if you stored it someplace.
    if (req.user == null) {
        return res.redirect('/');
    }
    return SamlStrategy.logout(req, function(err, uri) {
        return res.redirect(uri);
    });
});`

**Comment by vijaykotha** [comment]
@mbabar-cs Did the problem got solved?? Please could anyone help me as I am also getting the same error.

**Comment by mbabar-cs** [comment]
@vijaykotha Brother here is my updated code. Actually I reinitialize the samlStrategy  object and it's working fine. Below is my example code

`var SamlStrategy = require('passport-saml').Strategy;

var samlStrategy = new SamlStrategy({
    path: environment.oktaLoginCallbackURL,
    entryPoint: environment.oktaEntryPointURL,
}, function(profile, done) {
    return done(null, {
        id: profile.nameID,
        sessionIndex: profile.sessionIndex,
        email: profile.Email,
        firstName: profile.FirstName,
        lastName: profile.LastName,
        roles: profile.RoleInfo,
    });
});

 app.get('/logout', function(req, res) {
     console.log('In int----------------------------');
     //Here add the nameID and nameIDFormat to the user if you stored it someplace.
     if (req.user == null) {
         return res.redirect('/');
     }

      req.user.saml = {};
      req.user.saml.nameID = req.user.id;
      req.user.saml.nameIDFormat = req.user.id;


    req.user.id = req.user.saml.nameID;
    req.user.nameIDFormat = req.user.saml.nameIDFormat;


    samlStrategy.logout(req, function(err, request){
        if(!err){
            //redirect to the IdP Logout URL
            res.redirect(request);
        }
     });
 });`

**Comment by mbabar-cs** [comment]
If you still get same error then initialize var samlStrategy in **/logout** function.

**Comment by vijaykotha** [comment]
@mbabar-cs Thanks for the Response.
 Ok I did the same re initialization of Saml Strategy, its worked for me also.
 In the above code
samlStrategy.logout(req, function(err, request){
    if(!err){
        //redirect to the IdP Logout URL
        res.redirect(request);
    }
 });

The res.redirect(request); is redirecting to IDP logout url and its getting logged out but I am not able to redirect back to the entry point of SAML application  so that after I again logged in I should access the my application

Here is my logout callback route
router.post('/auth/saml/logout/callback', function(req,res){
	req.logout();
    res.redirect('/');
});

I did not figured it out Where to Configure this route. Please help me out

**Comment by mbabar-cs** [comment]
@vijaykotha Did you set logout Redirect callback in SAML configuration?

**Comment by vijaykotha** [comment]
passport.use(new SamlStrategy(
    {
      path: config.sso.path,
      entryPoint: config.sso.entryPoint,
      logoutUrl: config.sso.logoutUrl, // (https://idp.com/applogout)
      logoutCallback: config.sso.logoutCallback, //(/auth/saml/logout/callback)
      issuer: config.sso.issuer,
      cert: config.sso.cert
    },
    function (profile, done) {
    	var user = {};
    	user.email = profile.Email;
    	user.saml = {};
        user.saml.nameID = profile.nameID;
        user.saml.nameIDFormat = profile.nameIDFormat;
      return done(null,user);
    })
);
This is my SAML strategy object

I am able to logout of the application and also the IDP but on logout it should be redirected to the entry point of the application. Do we need to configure any metadata in the IDP??

**Comment by mwarrier** [comment]
@vijaykotha Did you ever figure out how to return to the app after logout? I'm facing the same issue

**Comment by zawars** [comment]
@mwarrier  I think you should try to redirect your application using HTTP status code 301 back to your login page or wherever to want. 
` res.writeHead(301, {
                Location: config.callbackRedirectUrl 
              });
`
