### ISSUE TITLE
wish: support request signing when binding method is http POST

### ISSUE THREAD

**Issue by benjamine** [node-saml/passport-saml#254]
I noticed that when providing a `privateCert`, Request gets signed only when using redirect binding, but when using http POST, there is no signature in the request xml.

Is there any plan to support request signing when binding method is http POST?

Example Request:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest
  xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
  AssertionConsumerServiceURL="https://......."
  Destination="https://......."
  ForceAuthn="false"
  ID="id1746722607943657199670241"
  IssueInstant="2017-12-28T05:25:44.659Z"
  Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">.......</saml2:Issuer>
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <ds:Reference URI="#id1746722607943657199670241">
        <ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <ds:DigestValue>barm+5fpFiKpbaPNF2OWzu3JElU=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>P5KvAwcWbILjXFsj......EnzA0RL/3GZQ==</ds:SignatureValue>
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509Certificate>MII.........FagWvpBrg==</ds:X509Certificate>
      </ds:X509Data>
    </ds:KeyInfo>
  </ds:Signature><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>
</saml2p:AuthnRequest>
```

**Comment by markstos** [comment]
> Is there any plan to support request signing when binding method is http POST?

There are plans for anything, that I'm aware of. The original authors are not currently participating in maintenance. I'm another `passport-saml` user who is pitching in to help a little, but already have a full plate. I periodically may check on PRs to see if they look mergable, but the project currently already "works for me", so I'm not looking to add features myself.

When evaluating change requests, I consider how they relate to the SAML specs. In this case, I would ask for link to the documentation confirming that signing HTTP requests is supported in the spec. (I expect that it is, but I think it's important to relate changes back to the SAML specs when possible).

**Comment by benjamine** [comment]
ok, thanks for the context 👍 
I'll add some reference links:
- http://saml.xml.org/forum/authnrequest-invalid-signature (a thread about signature being requested by IdP)
- and the specs: http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf (as mentioned in the link above), where at `3.2.1 Complex Type RequestAbstractType` mention:
```
<ds:Signature> [Optional]
An XML Signature that authenticates the requester and provides message integrity, as described
below and in Section 5.
```
and the schema:
``` xml
<complexType name="RequestAbstractType" abstract="true">
<sequence>
<element ref="saml:Issuer" minOccurs="0"/>
<element ref="ds:Signature" minOccurs="0"/>
<element ref="samlp:Extensions" minOccurs="0"/>
</sequence>
<attribute name="ID" type="ID" use="required"/>
<attribute name="Version" type="string" use="required"/>
<attribute name="IssueInstant" type="dateTime" use="required"/>
<attribute name="Destination" type="anyURI" use="optional"/>
<attribute name="Consent" type="anyURI" use="optional"/>
</complexType>
<element name="Extensions" type="samlp:ExtensionsType"/>
<complexType name="ExtensionsType">
<sequence>
<any namespace="##other" processContents="lax" maxOccurs="unbounded"/>
</sequence>
</complexType>
```

**Comment by benjamine** [comment]
I see this feature was added in 1.3.0, thank you 🙏 🎉 !!!
