### ISSUE TITLE
Releasing the SAML class as it's own module (or document how to use without Passport)

### ISSUE THREAD

**Issue by xylude** [node-saml/passport-saml#295]
Hi everyone!

I came across this library while trying to do a SAML implementation, but at first I decided to look elsewhere because I don't use passport in my application. I ended up coming across this library several times in my search for a non-passport version but never found one that was acceptable. I started to dig in to the source and found that the internal [saml.js](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js) file was usable as a standalone and could be directly imported, although I had to figure out a lot of the stuff by combing through the library and just figuring things out. Any chance of releasing that file as a standalone node SAML implementation?

PS - I'd be totally willing to help with the documentation since I already have a working version of my app using the saml.js file

**Comment by stavros-wb** [comment]
Hello @xylude I think asana maintains a fork of what you're proposing [here](https://github.com/Asana/node-saml-lib)

**Comment by xylude** [comment]
I think maintains might be a bit of a strong word, it's been 3 years since they've released any updates to it. Thanks though, I'll see about getting a PR in on that lib to bring it in to the present.

**Comment by markstos** [comment]
@xylude I'm a maintainer of `passport-saml` and am in favor of this idea.

The PR will be easiest to accept if it's shown that all the current tests for `passport-saml` pass with minimal modifications after it imports the SAML library. Perhaps your effort can be merged with Asana's efforts sometime in the future. It's helpfult to "@" mention in me in issues and pull requests. I don't watch all issue traffic by default-- I'm just another module user who has stepped up to help with maintenance.

**Comment by markstos** [comment]
@xylude I look forward to seeing this update happen.

**Comment by xylude** [comment]
After thinking about it for a bit I decided against submitting a PR to the Asana fork because I doubt that anyone besides me would be interested in keeping it from going stale again. Also I think it'd be weird to try and redirect issues/PRs over to this project since I wouldn't want to have the two libraries diverge.

Something I would totally be interested in doing is creating some readme documentation for the SAML lib that explains how to use it as a standalone class that you can use without passport. Would that be something that you'd be cool with @markstos?

**Comment by markstos** [comment]
@xylude It sound like you are suggesting leaving the library as-is, but explaining how to use it outside of Passport, which sounds good to me. Once that's done, the core description at the top of the README can be updated to note that the library can be used with or without Passport.

**Comment by markstos** [comment]
@sibelius That's a helpful example.

**Comment by markstos** [comment]
@xylude I've recently reviewed some other SAML libraries for Node as well as this one. `passport-saml` currently has the most weekly downloads and the most projects that depend on it. 

Other SAML projects do a good job at clearly communicating if they are providing code for the "Service Provider" (SP) role or the "Identity Provider" (IdP) role.  Our docs are not clear on that point.  If I'm not mistaken, `passport-saml` only helps with the Service Provider role. As part of documenting how the project can be used without `passport` that should be clarified.

I'm interested in putting out a 1.0 release in the next 10 days and would like to include these updated docs in the release if they are ready, including an example of using the project without `passport`.

**Comment by cjbarth** [comment]
The [passport-saml](https://github.com/node-saml/passport-saml) project has been forked to a [node-saml](https://github.com/node-saml/node-saml) project which focuses on the SAML part of [passport-saml](https://github.com/node-saml/passport-saml). Work in that repo will focus on stripping out the [Passport](https://github.com/jaredhanson/passport)-related code and having only what is needed for SAML auth.
