### ISSUE TITLE
wish: split tests into multiple files

### ISSUE THREAD

**Issue by markstos** [node-saml/passport-saml#310]
Right now all of our tests are in one giant file `test/test.js`.

I suggest breaking this up to more manageable files. Perhaps.

  * One test file for each file in `./lib/passport-saml/` that tests functions specific to a single file there
  * One more test file containing integration tests that involve tests that cover code in multiple files in `./lib`. 
  * Perhaps increased use of `./test/static` to store big blobs of XML and encrypted text so there is less clutter in the test files themselves.

**Comment by cjbarth** [comment]
I think we are actively working in this direction now with all the refactor. I think we can close this.
