### ISSUE TITLE
path to callback in metadata fails to include port number.

### ISSUE THREAD

**Issue by ahavriluk** [node-saml/passport-saml#322]
If no callbackUrl or path is specified, the generated location for AssertionCnsumerService in metadata is incorrect and misses the port number.
E.g. if I am running on port 3000, I would expect the default location to be 
http://localhost:3000/saml/consume
but 
http://localhost/saml/consume  
is generated instead.

PS. Even if path is specified, the port is still missing.

**Comment by andkrist** [comment]
> This method will only work on strategies which are configured with a callbackUrl (since the relative path for the callback is not sufficient information to generate a complete metadata document).

It seems you have to use callbackUrl to use this feature, or am I wrong?

**Comment by markstos** [comment]
@ahavriluk If you found a place where we could improve our handling of port numbers, a pull request is welcome.
