### ISSUE TITLE
Logout SLO is not working

### ISSUE THREAD

**Issue by umardraz** [node-saml/passport-saml#332]
Hello I am running PHPSAMLSSO, I have one wordpress website and one nodejs site.

Now the issue is whenever I am logged on both site using SSO and try to logout from wordpress site then it send/redirect me to my nodejs site.

But if I try to logout from nodejs site then both site successfully logout from SSO.

It means there might be issue with my code or passport-saml modules has lack of SLO (logout) functionality  here is my logout code 

```
app.get('/logout', function(req, res) {
  samlStrategy.logout(req, function(err, request) {
    if (!err) {
      res.redirect(request);
    }
  });
});

app.get('/logout/callback', function(req, res) {
  req.logout();
  res.redirect('/');
});
```

Please help me how I can solve this issue

**Comment by stavros-wb** [comment]
@umardraz make sure you:
• Use the latest passport-saml release (1.0.0)
• Configure SimpleSAMLphp with SingleLogoutService (for the node project) to point to the `/logout` endpoint, so it uses the `samlStrategy.logout` as well

**Comment by christiaanwesterbeek** [comment]
And also, I believe that:

`app.get('/logout/callback'...`

actually should be:

`app.post('/logout/callback'...`

See: https://github.com/bergie/passport-saml/issues/221#issuecomment-338896096

**Comment by cjbarth** [comment]
Closed due to inactivity.
