### ISSUE TITLE
Include Profile Object Type in Dependency or DefinitelyTyped

### ISSUE THREAD

**Issue by theaccordance** [node-saml/passport-saml#333]
The README.md document outlines a type for the profile object, but that type doesn't appear to exist within the project itself, or in the @types/passport-saml dep from DefinitelyTyped.  

Is there by chance someone who can quickly remedy this, or do I need to set time aside to contribute the fix myself? I'm not opposed to contributing, I'm just not up-to-speed on the contribution process for DefinitelyTyped

**Comment by cjbarth** [comment]
This should be resolved now that we have a TypeScript-based version of `passport-saml` released.
