### ISSUE TITLE
Can't change authnRequestBinding from HTTP-Post

### ISSUE THREAD

**Issue by Kevin-Chung** [node-saml/passport-saml#336]
Hi, 

I'm having issues changing the authnRequestBinding parameter from `HTTP-POST` to `HTTP-Redirect`. I have tried adding it at the top level of the object given to `SamlStrategy`, inside of `additionalAuthorizeParams`, and inside of `additionalParams`. 

```
passport.use(new SamlStrategy(
  {
    callbackUrl: 'callbackurl,
    entryPoint: 'entrypoint,
    issuer: 'issuer',
    signatureAlgorithm: 'sha1',
    privateCert: '...',
    cert: '...',
    forceAuthn: true,
    isPassive: false,
    identifierFormat: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
    authnRequestBinding: 'HTTP-Redirect',
    additionalAuthorizeParams: {
      authnRequestBinding: 'HTTP-Redirect',
    },
    additionalParams: {
      authnRequestBinding: 'HTTP-Redirect',
    },
  },
  function( profile, done ) {
    return done(null, profile});
  }
));
```

Looking at [the saml.js file](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L166) it seems that the protocolbinding property is hardcoded, if I modify this file under my node_modules directory it successfully changes the protocol binding.

Please let me know if I've done something wrong with this configuration.

## Sample generated SAML request 
```<?xml version="1.0"?>
<samlp:AuthnRequest AssertionConsumerServiceURL="URL"
    Destination="URL" ForceAuthn="true" ID="ID"
    IssueInstant="2019-01-15T20:48:34.890Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:**HTTP-POST**" Version="2.0"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">URL</saml:Issuer><samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"/>
    <samlp:RequestedAuthnContext Comparison="exact" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
        <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>```

**Comment by Kevin-Chung** [comment]
As a random sidenote, it seems the isPassive parameter is also not honored, it does not seem to be set in the `initialize()` function

**Comment by virginc** [comment]
I am also having this issue.

**Comment by crutley** [comment]
I am certainly not an expert, but it seems to me that the **HTTP-POST** highlighted in the example describes what binding the service provider (passport-saml) is expecting for the SAML response from the identity provider.  I don't think it has anything to do with the authnRequestBinding parameter, which determines the binding type for the AuthnRequest.

From the SAML spec, "3.4.1 Element <AuthnRequest>":

> ProtocolBinding [Optional]
> A URI reference that identifies a SAML protocol binding to be used when returning the <Response>
> message.

So the module seems to be operating correctly in this regard.

**Comment by stevenmasci** [comment]
I am also having this issues. The HTTP Binding for SAML responses cannot be configured as it is hardcoded (to HTTP-POST).

**Comment by cjbarth** [comment]
It seems that the original problem is in [this](https://github.com/node-saml/passport-saml/blob/677424cf2f594344e4e70bec0be2d7591a60e089/lib/passport-saml/saml.js#L166) line. The current code reads like [this](https://github.com/node-saml/passport-saml/blob/6ba76ba3a015fea96a2dd38f661a6c1f85bc44a1/src/node-saml/saml.ts#L252), which is largely the same, so this is still an open issue. If someone would like to make a PR to address this matter, please feel free to do so against the `node-saml` project where this code now lives.

**Comment by srd90** [comment]
SAML conformance requrements ( http://docs.oasis-open.org/security/saml/v2.0/saml-conformance-2.0-os.pdf ) document's paragraph 2 table 1 lists following bindings for authn Responses (from IdP to SP): `HTTP POST` and `HTTP artifact`.

SAML profiles ( http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf ) document's paragraph 4.1.2's web sso messaging flow says about responses:
> In step 5, the identity provider issues a `<Response>` message to be delivered by the user agent to the service provider. Either the HTTP POST, or HTTP Artifact binding can be used to transfer the message to the service provider through the user agent. …

`passport-saml` does not support artifact binding at all.

So based on whats being stated above there should not be any reason to be able to alter auth response binding from HTTP post to anything.

ping @Kevin-Chung  @vi-cat @stevenmasci
