### ISSUE TITLE
Question: How to access request 'ID' and response 'InResponseTo' fields?

### ISSUE THREAD

**Issue by ahavriluk** [node-saml/passport-saml#337]
Hi!

In my SP implementation, I would like to log out the SAML request ID field and InResponseTo field from SAML response for correlation purposes. How do I get access to those fields from passport-saml lib?

Thank you!

**Comment by jgomer2001** [comment]
I would do this:

```
user.getAssertion()['Assertion']
	['Subject'][0]
	['SubjectConfirmation'][0]
	['SubjectConfirmationData'][0]
	['$']['InResponseTo']
```

**Comment by markstos** [comment]
That's pretty unwieldy. It seems a like a shortcut would be helpful. Further conversation about possibly adding that shortcut can continue in #393
