### ISSUE TITLE
SAML Subject confirmation fails on more than subject confirmation

### ISSUE THREAD

**Issue by Kevin-Chung** [node-saml/passport-saml#339]
I am currently running into an issue where my SAML response object has multiple subject confirmation tags, and saml-passport is throwing an error `Unable to process multiple SubjectConfirmations in SAML assertion`. Looking through the source code, if a SAML response object has more than one `<saml2:SubjectConfirmation>` nested within a `<subject>` tag then [an error is thrown](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L913). 

This was unexpected behavior for me since the [SAML core specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) states that there can be "zero or more" subject confirmations. 

Is this expected behavior? If so can someone help me with how to approach this issue when I receive multiple subject confirmation tags?

**Comment by afurlane** [comment]
I'm going to open a pull request for this bug; it's my first time on github, so be patient.
