### ISSUE TITLE
Logout with HTTP POST binding

### ISSUE THREAD

**Issue by benbrown-work** [node-saml/passport-saml#357]
Our IDP uses HTTP-POST bindings for login and logouts.
Our login setup is working fine and I see that logout should also work for HTTP-POST binding from the [README logout section](https://github.com/bergie/passport-saml/blob/master/README.md#slo-single-logout).
 
For logout from the examples and code, it seems that only HTTP-Redirect is an option unless I am missing something or our IDP is implemented differently than others.
 
In all the examples I see, the initial call to SP logout is something like this.
```
strategy.logout(req, function (error, requestURL)  {
                req.logout();
                req.redirect(requestUrl); 
}
```

It would seem in the HTTP-POST scenario that req.redirect needs to be sending back more something like what happens with getAuthorizeForm in [strategy.js#L91](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/strategy.js#L91)
  
In our strategy.logout callback, if we emulate something similar, making a POST request with the data returned from generateLogoutRequest, we can get the SP logout to happen. 

Simple example (createPostMessage is similar in ways to [getAuthorizeForm](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L395)): 
```
expressApp.get('/auth/signout', (req, res) => {
    const samlRequest = samlStrategy._saml.generateLogoutRequest(req);
    const encodedSamlRequest = Buffer.from(samlRequest, 'utf8').toString('base64');
    samlStrategy.logout(req, () => {
        const samlMessage = {
            SAMLRequest: encodedSamlRequest
        };
        createPostMessage(samlMessage, function(err, data) {
            res.send(data);
        });
    });
});
```

Would this be the recommended way to do a HTTP-POST logout?  

Or have I missed something and not finding the correct http post logout examples?  In reviewing other issues on http post logouts, I haven't really seen answers or they seem to be able to go back and use the http redirect method which I cannot do with our IDP.

Would this be something that would be beneficial in the module or just something handled like the example above?

Thanks

**Comment by markstos** [comment]
@josecolella Here's another logout issue to consider while you are looking at others.

**Comment by BenBullock1992** [comment]
Any update on this please?

**Comment by cjbarth** [comment]
We're just released v4. Is this still an issue?
