### ISSUE TITLE
Uncatchable exception when parsing entryPoint

### ISSUE THREAD

**Issue by gunzip** [node-saml/passport-saml#415]
In a MultiStrategy, `getSamlOptions` may not find a suitable entrypoint to pass to the saml client
so we end up with entryPoint = undefined. This causes the NodeJS process to crash since these lines here: https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L307
contain an uncheck call to `url.parse` which throws since entryPoint is not defined. As we are in a callback there's no way to catch the exception and the process exits. I guess the whole method should be wrapped in a try / catch block (not that this may be used as a DoS against the service provider)

**Comment by markstos** [comment]
@gunzip Are you willing to contribute a pull request to improve this?  Thanks for the report.

**Comment by googamanga** [comment]
Hitting this issue to, getting unhandledPromise error if running "return done(new Error('saml not found'))" inside of getSamlOptions

**Comment by googamanga** [comment]
@gunzip is there a work around?

**Comment by cjbarth** [comment]
This problem is no longer in this repository. The affected code is now in [`node-saml`](https://github.com/node-saml/node-saml). If the problem persists, please re-open this over there.
