### ISSUE TITLE
"invalid signature" when using xml-crypto > 1.4.0

### ISSUE THREAD

**Issue by mightypenguin** [node-saml/passport-saml#431]
Not sure why, but xml-crypto > 1.4.0 gives me an invalid signature.
Fix is to force xml-crypto to v1.4.0

But perhaps there's something programmatic that needs to change in how passport-saml is using it?

**Comment by mightypenguin** [comment]
Possibly related bug report on that package.

https://github.com/yaronn/xml-crypto/issues/200

**Comment by thenengah** [comment]
@mightypenguin 

We also ran into this. I submitted a fix of it here:
https://github.com/yaronn/xml-crypto/pull/211

But the xml-crypto team thinks this update doesn't belong in xml-crypto.

@bergie what are your thoughts about normalizing line-breaks before `checkSignature`. Something like this should work:
```
// windows line breaks botch sha digests alogs
fullXml = fullXml.string.replace(/\r\n?/g, '\n');
sig.checkSignature(fullXml);
```

**Comment by markstos** [comment]
@thenengah Please create a PR for this which includes a test case that illustrates the failure. You should hopefully be able to find a matching test, copy/paste and add some Carriage Returns to it.

I looked up the XML spec for newlines. It is here:

https://www.w3.org/TR/REC-xml/#sec-line-ends

It says that the XML *processor* should normalize the newlines as you describe before *parsing*. 

I look up related references in `xml-crypto` and it sounds like `xml-crypto` expects us to be the "XML Processor" while it serves as the "parser". 

So, it does seem to be correct according to the spec for us to normalize the newlines before handing off XML to `xml-crypto`.

**Comment by mhassan1** [comment]
@markstos PR here: https://github.com/node-saml/passport-saml/pull/498
