### ISSUE TITLE
generateServiceProviderMetadata missing SOAP Logout option

### ISSUE THREAD

**Issue by thcase** [node-saml/passport-saml#443]
There are three logout methods for SAML (HTTP-REDIRECT, HTTP-POST, and SOAP).  The generateServiceProviderMetadata doesn't support generating the SOAP logout callback.  Suggest adding a property called something like "logoutSOAPCallbackUrl" and then adding something similar after the logoutCallbackURL option check in the saml.js (currently lines 1273-1278).

```javascript
if (this.options.logoutSOAPCallbackUrl) {
    metadata.EntityDescriptor.SPSSODescriptor.SingleLogoutService = {
      '@Binding': 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP',
      '@Location': this.options.logoutSOAPCallbackUrl
    };
  }
```

For now, if this was in the project, I can generate Metadata for SP initiated logins that require SOAP logout paths.  The actual handling of the SOAP logout response would be up to the client, but should be similar to a request for HTTP-POST (both are POST methods, with the latter having XML for the body -- needing an XML Body Parser to handle response).

**Comment by thcase** [comment]
For background, I am working on project interfacing with Cerner EHR that still uses SOAP for SP initiated connections (ref: [https://dev.cernerhealth.com/doc/api/oauth/sign-in-with-cerner-health-saml](https://dev.cernerhealth.com/doc/api/oauth/sign-in-with-cerner-health-saml)).

**Comment by thcase** [comment]
Actually just saw this pull request, which may meet the same need, w/o need of additional option variable.

[https://github.com/node-saml/passport-saml/pull/440/commits/d730c3b47bbfed3b2d5672fac72b3844e08a480b](https://github.com/node-saml/passport-saml/pull/440/commits/d730c3b47bbfed3b2d5672fac72b3844e08a480b)

**Comment by cjbarth** [comment]
The author of that PR closed it without addressing review comments. We are preparing to release v3 in the next few weeks. If you're willing to create a PR for this fix, we'll try to work with you to get it landed.
