### ISSUE TITLE
Renewing session with IsPassive

### ISSUE THREAD

**Issue by cking285** [node-saml/passport-saml#450]
Is there any example anywhere of how to configure this module to renew/check that a session is still valid with the IDP using the IsPassive parameter in the SAML AuthnRequest?

It would be ideal if `passport-saml` could be configured as middleware to renew the users session with the IDP upon each request.

**Comment by markstos** [comment]
I'm sorry, there aren't resources here for support questions. If you are certain there's a bug or a missing feature according to the spec, please open a new issue. Thanks.
