### ISSUE TITLE
SAML.prototype.validatePostRequest issues

### ISSUE THREAD

**Issue by thcase** [node-saml/passport-saml#452]
I ran into issue when working with the library concerning the `saml.js` library method `SAML.prototype.validatePostRequest` method.  Line 1091 assumes the input to the function to be Base64 encoded:

```
  const xml = Buffer.from(container.SAMLRequest, 'base64').toString('utf8');
```

In the POST request I am working with that comes from Cerner's Patient Portal, which uses python SAML library, the request is in plaintext.  An option may need to be added and check here for format of POST Request.

Also, the xml2js parserConfig on lines 1093-1097 assumes **strict** parsing.  In order for the parsing to work with the plaintext xml sent, I needed.  One may need a configuration option for this also with default to strict.

Original
```
const parserConfig = {
    explicitRoot: true,
    explicitCharkey: true,
    tagNameProcessors: [xml2js.processors.stripPrefix]
  };
```
Revised
```
const parserConfig = {
    explicitRoot: true,
    explicitCharkey: true,
    tagNameProcessors: [xml2js.processors.stripPrefix],
    strict: false
  };
```

**Comment by markstos** [comment]
Please reference what the SAML spec says what the encoding should be here.

**Comment by thcase** [comment]
I am not sure if [this](http://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) is the proper specification.  The SOAP Binding Protocol is specified in section 3.2.  The XML is in plain text as opposed to HTTP-POST where the XML appears to be Base64 encoded (section 3.5).  The SLO callback via SOAP is an HTTP POST call that happens with the IDP notifies SP that it has received a logout action (i.e., it notifies all SP's of logout action).  I can't change the IDP's setup (in this case Cerner).  They have a lot of clients that use the system as is.  What I am asking for is flexibility in the Passport SAML library to be able to handle the SOAP logout w/o having to maintain my own version of the library, which is what I will currently have to do.

**Comment by markstos** [comment]
I'm OK with supporting the requested flexibility as well as the current behavior remains the default.

 * Strict parsing seems like safer default
 * From your reading of the spec, it seems like base64 is also a spec-compliant choice.

A pull request to implement this should also update the docs and ideally the tests as well.
