### ISSUE TITLE
Unexpected openssl exception while calling signRequest

### ISSUE THREAD

**Issue by liweixi100** [node-saml/passport-saml#458]
I am stuck with the following error and would appreciate any help. 

```
`Error: error:02001002:system library:fopen:No such file or directory
    at Sign.sign (internal/crypto/sig.js:105:29)
    at SAML.signRequest (/mybackend/node_modules/passport-saml/lib/passport-saml/saml.js:137:38)
    at DeflateRaw.requestToUrlHelper [as cb] (/mybackend/node_modules/passport-saml/lib/passport-saml/saml.js:313:12)
    at DeflateRaw.zlibBufferOnEnd (zlib.js:149:10)
    at DeflateRaw.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  opensslErrorStack: [
    'error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib',
    'error:2006D080:BIO routines:BIO_new_file:no such file'
  ],
  library: 'system library',
  function: 'fopen',
  reason: 'No such file or directory',
  code: 'ERR_OSSL_SYS_NO_SUCH_FILE_OR_DIRECTORY'
}
```
`

* Extensive google search did not reveal anything helpful. 
* There was no file to open since the `SAML.signRequest` API takes a key (string). 
* I have verified the `privateCert` passed to `signRequest` was in the required multiline RSA format (through logging). 
* This exception only occurs in our production environment but not our development environment. 
* Not sure why "X509 certificate routine" was involved while the private key was in RSA format. 

Any help would be greatly appreciated. (Apology for the `bug` label, I don't know how to remove it.)

**Comment by cjbarth** [comment]
Without tracing through the code myself to see how one might arrive at this code, and without the config file as a sample, there isn't much to say. However, in the past, when I've had issues like this, what stands out to me is that the exception occurs only in production not development, in which case two things come to mind:

1. Incomplete deployment; some of the errors in this code don't pop up exactly where one might expect them, leading to some confusion. It may be your missing some other cert material and it is just showing up here at a time you don't expect it.
2. Permissions variance; production permissions are rarely the same as on a development machine. Is there some way to compare the permission of the folders your working with locally to those that are on the server? Or maybe use a container (like Docker) for testing more server-like when local?

**Comment by liweixi100** [comment]
This turned out to be an issue with our own node build. We don't known what went wrong exactly, but the issue has nothing to do with passport-saml.
