### ISSUE TITLE
SAML provider returned Responder error: unspecified (sha256)

### ISSUE THREAD

**Issue by Crispy1975** [node-saml/passport-saml#467]
I've been using `passport-saml` for a while and it has performed well with `sha1` certificates and keys (ADFS and other IdPs). However I have recently added `sha256` certs and keys and I am now getting the following error back on trying to sign-in with an ADFS server.
```
payload: {
      error: "Bad Request"       
      message: "SAML provider returned Responder error: unspecified"       
      statusCode: 400       
     }
     statusCode: 400      
    }
    stack: "Error: SAML provider returned Responder error: unspecified
    at /src/node_modules/passport-saml/lib/passport-saml/saml.js:679:31
    at _fulfilled (/src/node_modules/q/q.js:854:54)
    at /src/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/src/node_modules/q/q.js:816:13)
    at /src/node_modules/q/q.js:570:49
    at runSingle (/src/node_modules/q/q.js:137:13)
    at flush (/src/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)"     
    statusXml: "<Status>
  <StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/>
</Status>"     
   }
  }
```
The error on the ADFS side shows the following:
![image002](https://user-images.githubusercontent.com/12525875/96711228-2367eb80-1395-11eb-9120-268e7bc608a6.png)

Now... looking at the ADFS event log it's obvious what the error actually is. ADFS is expecting a `sha256` signature algorithm, but it's getting `sha1`. And it is here the issue lays, as best I can tell I have configured everything within `passport-saml` to only send `sha256`. What follows is the setup (with sensitive data and error handling removed for brevity):

I load the SAML library as follows (I am using Hapi.js and not Express):
```
const samlLib = require('passport-saml/lib/passport-saml/saml');
```
The SAML options passed into the constructor to generate the metadata is as follows:
```
const samlOptions = {
    logoutCallbackUrl: '<logout-url>',
    callbackUrl: '<callback-url>',
    issuer: '<assertion-url>',
    privateCert: '<private-key>',
    decryptionPvk: '<private-key>',
    signatureAlgorithm: 'sha256',
    digestAlgorithm: 'sha256',
    identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    disableRequestedAuthnContext: true
};

const saml = new samlLib.SAML(samlOptions);
const metadataXml = saml.generateServiceProviderMetadata(samlCrt, samlCrt);
```
This generates the metadata as expected with both the signing and encryption X509 elements. I've checked the certs with `openssl` and both report as being `sha256`. This is imported into the ADFS server.

As the service provider (SP) I am providing an endpoint for users to hit to start the SSO process. This endpoint generates the required SAML payload and redirects the user to their ADFS IdP. This code use for this is:
```
const samlOptions = {
    logoutCallbackUrl: '<logout-url>',
    callbackUrl: '<callback-url>',
    issuer: '<assertion-url>',
    privateCert: '<private-key>',
    decryptionPvk: '<private-key>',
    signatureAlgorithm: 'sha256',
    digestAlgorithm: 'sha256',
    identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    disableRequestedAuthnContext: true,
    entryPoint: '<login-url>',
    cert: '<user-provided-public-cert>'
};

const saml = new samlLib.SAML(samlOptions);
saml.getAuthorizeUrl({ headers: request.headers, body: request.payload, query: request.query }, samlOptions, (err, loginUrl) => {
    return reply.redirect(loginUrl);
});
```
Again this redirect works, however I have used a Chrome extension to capture what is being sent, that looks as follows...
![screenshot_2020-10-20_at_10 50 25](https://user-images.githubusercontent.com/12525875/96713808-15b46500-1399-11eb-8ff7-e3e6d015900b.png)
As can be seen in the above grab the `SigAlg` seems to be `sha1` however I believe I have set everything to `sha256` correctly.

If the ADFS server is set to expect `sha1` the sign-in works correctly. If it is set to `sha256` I get the above ADFS error.

The assertion handler code is as follows for completeness...
```
const samlOptions = {
    logoutCallbackUrl: '<logout-url>',
    callbackUrl: '<callback-url>',
    issuer: '<assertion-url>',
    privateCert: '<private-key>',
    decryptionPvk: '<private-key>',
    signatureAlgorithm: 'sha256',
    digestAlgorithm: 'sha256',
    identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    disableRequestedAuthnContext: true,
    entryPoint: '<login-url>',
    cert: '<user-provided-public-cert>'
};

const saml = new samlLib.SAML(samlOptions);
saml.validatePostResponse(request.payload, (err, profile) => {
    if (err) {
        throw new Error(err);
    }
    // Do further checks and sign the user in (at this point I can see a log of the decoded data when set to sha1)
}
```
The error thrown in the above code is where the error output at the top of this post is logged from. The question here is have I missed something or is there a possible bug in the library when using `sha256`? Up until now everything has worked well for `sha1`.

**Comment by cjbarth** [comment]
Question, what happens if you leave the `digestAlgorithm` as the default? I know `sha256` does work for [signing](https://github.com/node-saml/passport-saml/blob/026edf2a422f70ee8f483c902594bf29a27def3c/test/tests.js#L1421), but I don't know about digest. We may need more test coverage here.

**Comment by Crispy1975** [comment]
@cjbarth I tried without the `digestAlgorithm` as default, exactly the same error message as reported.

**Comment by cjbarth** [comment]
It seems there may be something else at play here. Can you break the code to make sure that your provided options are actually being read. I ask because we have test coverage for this case [here](https://github.com/node-saml/passport-saml/blob/370ee9f03366f50cb4e346db95b9cb29834dea24/test/saml-post-signing-tests.js#L28). It is hard to imagine there would be a bug [here](https://github.com/node-saml/passport-saml/blob/370ee9f03366f50cb4e346db95b9cb29834dea24/lib/passport-saml/algorithms.js#L17) or [here](https://github.com/node-saml/passport-saml/blob/370ee9f03366f50cb4e346db95b9cb29834dea24/lib/passport-saml/saml-post-signing.js#L18) or [here](https://github.com/node-saml/passport-saml/blob/370ee9f03366f50cb4e346db95b9cb29834dea24/lib/passport-saml/algorithms.js#L6).

**Comment by Crispy1975** [comment]
Ok, so I ran a debug session from the API and grabbed the following for the SAML options passed in `getAuthorizeUrl()`, there is some weirdness going on with both the `signatureAlgorithm` and the `digestAlgorithm`. I suspect this could be the cause as it's not a known algorithm string... so it falls back to `sha1`?

![Screenshot 2020-10-23 at 11 21 49](https://user-images.githubusercontent.com/12525875/96993176-d7e34800-1522-11eb-963b-81a48a8bfdb8.png)

I will investigate this a little further and report back.

**Comment by Crispy1975** [comment]
I traced this back to a problem with base64 encoded strings. Everything seems to work as expected now. Thanks for taking the time to reply. :)
