### ISSUE TITLE
error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by ishanuda** [node-saml/passport-saml#499]
Hi,
I am using the passport-saml along with the Nest.JS.

The settings of the strategy is the following:

```
export default () => ({
    strategy: {
        issuer: process.env.ISSURE,
        entryPoint: process.env.ENTRY_POINT,
        callbackUrl: process.env.CALLBACK_RUL,
        redirectUrl: process.env.REDIRECT_URL,

        logoutUrl: process.env.LOGOUT_URL,
        logoutCallbackUrl: process.env.LOGOUT_CALLBACK_RUL,
        
        privateCert: process.env.PRIVATE_CERT ? fs.readFileSync(process.env.PRIVATE_CERT, 'utf-8') : '',
        decryptionPvk: process.env.PRIVATE_KEY ? fs.readFileSync(process.env.PRIVATE_KEY, 'utf-8') : '',

        identifierFormat: process.env.IDENTIFIER_FORMAT,
        authnContext: process.env.AUTHN_CONTEXT === 'true',
    },
});
```
With the above settings before re-directing to the idp server I am getting the following error:

```
error:0909006C:PEM routines:get_name:no start line - 
Error: error:0909006C:PEM routines:get_name:no start line\n    
at Sign.sign (internal/crypto/sig.js:80:26)\n    
at SAML.signRequest (node_modules\\passport-saml\\lib\\passport-saml\\saml.js:142:34)\n    
at DeflateRaw.requestToUrlHelper [as cb] (node_modules\\passport-saml\\lib\\passport-saml\\saml.js:333:14)\n    
at DeflateRaw.zlibBufferOnEnd (zlib.js:131:10)\n    
at DeflateRaw.emit (events.js:203:15)\n    
at endReadableNT (_stream_readable.js:1145:12)\n    
at process._tickCallback (internal/process/next_tick.js:63:19)
```
**NOTE: However with the configuration, I can generate the metadata.xml file using the method
`generateServiceProviderMetadata` without any errors.**

Am I missing some settings or configured with the wrong values in the above config?

I also tried with several cert/key but the error was the same.

**NOTE: the cert/key did generate using an online self-sign certificate generator.**

Everything is working fine if I remove the `privateCert/ decryptionPvk` from the config

My env is as the following:

> OS: Windows 10
> Node Version: v10.16.3
> typescript: v4.0.3
> Nest.JS: v7.4.4
> nestjs/passport: v7.1.0
> passport: v0.4.1
> passport-jwt: v4.0.0
> passport-saml: v1.3.5

**I also looked into the following URLs, but with no success:**

[stackoverflow question 1](https://stackoverflow.com/questions/22584268/node-js-https-pem-error-routinespem-read-biono-start-line/34004949)

[stackoverflow question 1](https://stackoverflow.com/questions/40622251/which-files-use-for-saml-with-passport-saml)

> NOTE: The same error is coming on the deployed server as well.

Thank you

**Comment by cjbarth** [comment]
Can you capture the values that are sent to `Sign.sign` and see if the cert is what you are expecting? Or, perhaps you could write a unit test that duplicates this behavior.

This may be a similar issue to what was commented on here: https://github.com/node-saml/passport-saml/issues/494#issuecomment-723348603

**Comment by ishanuda** [comment]
Hi @cjbarth,
Thank you for your reply.

I wonder how **@aloswald** set up the application to work with the v1.3.5 as he mentions in the comment.
Also, he says updating the library is giving the error.
[Comment](https://github.com/node-saml/passport-saml/issues/494#issuecomment-723348603)

Regards.

**Comment by ishanuda** [comment]
Hi @gugu,

I just applied what the `keyToPEM(key)` method does with your fix as a local method just to check.

```
/**
 * Test for the issue 499 with @gugu's fix
 * @see https://github.com/node-saml/passport-saml/issues/499
 */
export function clean(key: string) {
    if (!key || typeof key !== 'string') return key;
  
    const lines = key.split(/\r?\n/);
    if (lines.length !== 1) return key;
  
    const wrappedKey = [
      '-----BEGIN PRIVATE KEY-----',
      ...key.match(/.{1,64}/g),
      '-----END PRIVATE KEY-----',
      ''
    ].join('\n');
    return wrappedKey;
}
```

But no luck and the issue exists still.

Thank you very much.

**Comment by aloswald** [comment]
@ishanuda You are welcome to look, the project I was working is open source.
[https://github.com/uwwebservices/UWER/blob/7347734fdf8919d57d47d69a238afda0a40294d5/src/backend/index.js#L67](https://github.com/uwwebservices/UWER/blob/7347734fdf8919d57d47d69a238afda0a40294d5/src/backend/index.js#L67)

**Comment by ishanuda** [comment]
Hi @aloswald,

Thank you very much for the link.
I will check it and get back to you.

Regards.
