### ISSUE TITLE
[BUG] Release 2.0.3 not published to NPM

### ISSUE THREAD

**Issue by mhassan1** [node-saml/passport-saml#519]
I see tag https://github.com/node-saml/passport-saml/releases/tag/v2.0.3 from 12 days ago, but I don't see a new release on [NPM](https://www.npmjs.com/package/passport-saml). Are we waiting for something before publishing?

**Comment by markstos** [comment]
Checking.

**Comment by markstos** [comment]
It should be released in about 15 minutes, so I'll go ahead and close this.

**Comment by markstos** [comment]
Released. There were internal changes related to the changelog format, so the release is v2.0.4.
