### ISSUE TITLE
How to get SamlStrategy parameters from db

### ISSUE THREAD

**Issue by umardraz** [node-saml/passport-saml#522]
Hi

I want to get these values from MySQL DB instead of static config file or from .env

```
passport.use(new SamlStrategy(
  {
   entryPoint: get_from_db?
   issuer: get_from_db?
   callbackUrl: get_from_db?
  }

```
is it possible? if yes then would you please help me how I can do this?

**Comment by markstos** [comment]
Support is not provided here. You can try StackOverflow with `passport-saml` tag.
