### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dosullivan557** [node-saml/passport-saml#525]
When installing the module, we pull in .pem files and .key files which causes our application to fail security scans. As part of the install, we should not move these files in.

**Comment by cjbarth** [comment]
I'm not sure what bug you are reporting. Can you please provide a clear test case, perhaps even a new unit test that fails?

**Comment by dosullivan557** [comment]
It's not an issue with the code, because we install your module in an application, it copies over .pem and .key files that are in your tests. This means that when we put our application through security scans, it fails because it finds these files and classifies them as sensitive data. What I'm asking is whether you can not include these in the bundled version of the application.

To resolve it, you can have a file called .npmignore and specify the paths, which will then not copy those files over to the build of the module.

**Comment by cjbarth** [comment]
That seems reasonable. Can you make a PR?

**Comment by dosullivan557** [comment]
Thanks @cjbarth  - PR raised

**Comment by dosullivan557** [comment]
Merged in - @cjbarth when could I expect it to be release to use?

**Comment by cjbarth** [comment]
Released as v2.0.5
