### ISSUE TITLE
[BUG] Unable to override default authnRequestBinding when using MultiSamlStrategy 

### ISSUE THREAD

**Issue by mhesler74** [node-saml/passport-saml#528]
passport.authenticate only uses the default authnRequestBinding setting when using the MultiSamlStrategy class.
Providing an alternative authnRequestBinding setting as a return value in the getSamlOptions function is completely ignored.

**Comment by cjbarth** [comment]
Would you be willing to make a PR to address this @mhesler74 ?

**Comment by stavros-wb** [comment]
It's currently a "global" passport configuration
https://github.com/node-saml/passport-saml/blob/43465d6b4957218b05ca040dd5c8d853a1208cbd/test/multiSamlStrategy.js#L136
Do you need it, to be set per client?

**Comment by mhesler74** [comment]
Yes, I need it set per client.  Some of our customers are using HTTP-Request binding for authentication while others support HTTP-POST.

**Comment by mhesler74** [comment]
Actually another PR was put in a while back by someone else... very similar
https://github.com/node-saml/passport-saml/pull/432

**Comment by mhesler74** [comment]
Any ETA on when this will be included in a release?

**Comment by cjbarth** [comment]
I believe this is part of the v3 release, which is held up due to some missing code reviews. See https://github.com/node-saml/passport-saml/milestone/1.
