### ISSUE TITLE
passport-saml with sailsjs, profile callback is never executed [BUG]

### ISSUE THREAD

**Issue by ramonluis1987** [node-saml/passport-saml#537]
I am trying to integrate with OKTA SAML 2.0 but for some reason, the callback is not executed. Any idea? Thanks

```js
passport.use(new SamlStrategy({
    path: '/v1/callback',
    callbackUrl: 'http://localhost:8080/v1/callback',
    entryPoint: 'https://xxxx/sso/saml',
    issuer: 'http://www.okta.com/xxxxxxx',
    cert: './cert/okta.cert',
    passReqToCallback: true,
    logoutUrl: 'http://localhost:8080/v1/logout',
  },
  function(profile, done) {
    console.log(profile, done);
    return done(null, profile);
  })
);
```

**Comment by cjbarth** [comment]
Why do you say this is a bug? Could you please provide a test that fails? Others have used `passport-saml` with OKTA without issues.

If this is just a question about how to use `passport-saml`, you might have better success asking this question on StackOverflow: https://stackoverflow.com/questions/tagged/passport-saml

**Comment by markstos** [comment]
No further follow up and it's not clear it's our bug. Closing.
