### ISSUE TITLE
1.x.x to 2.x.x migration type issue

### ISSUE THREAD

**Issue by vbodnia** [node-saml/passport-saml#540]
Env: Node 14.15.4
Typescript 4.1.3

Currently, I am using passport-saml@1.5.0 with @types/passport-saml@1.1.2. After updating to 2.0.5 I've got a type error in MultiSamlStrategy saying:

> TS2345: Argument of type 'MultiSamlStrategy' is not assignable to parameter of type 'Strategy'. Types of property 'authenticate' are incompatible. Type '(req: RequestWithUser, options: AuthenticateOptions & AuthorizeOptions) => void' is not assignable to type '(this: StrategyCreated<Strategy, Strategy & StrategyCreatedStatic>, req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, options?: any) => any'. Types of parameters 'req' and 'req' are incompatible. Property 'samlLogoutRequest' is missing in type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' but required in type 'RequestWithUser'.

The problem is that I'm also extending express requests with custom fields, e.g. user.

**Comment by cjbarth** [comment]
The latest build of `passport-saml` includes its own types and doesn't need anything from DefinitelyTyped.

**Comment by vbodnia** [comment]
@cjbarth In fact, the same issue happens without @types/passport-saml package. I have reinstalled modules with the version 2.0.5 and got the same error.

**Comment by Mikescops** [comment]
I confirm what @vbodnia says, please reopen this issue, it's a current bug in v2.0.5.

**Comment by cjbarth** [comment]
Is this a bug at the `HEAD` of `master`?

**Comment by vbodnia** [comment]
@cjbarth Yes it is:

![image](https://user-images.githubusercontent.com/32565392/113671508-1f1f5880-96bf-11eb-9743-f8c8d4e433af.png)
![image](https://user-images.githubusercontent.com/32565392/113671523-234b7600-96bf-11eb-9dae-a5c5cd738852.png)
![image](https://user-images.githubusercontent.com/32565392/113671538-26466680-96bf-11eb-88cd-9b39c94d03e0.png)

**Comment by cjbarth** [comment]
It seems this might be related to #549. Would you agree?

In any case, I can't see from your screen shot exactly what the problem is. Do you have some sample code I can load up?

**Comment by fluggo** [comment]
The screen shot doesn't show it, but the original description is very similar to mine. I haven't gone back with tweezers yet to figure out where mine went wrong.

**Comment by vbodnia** [comment]
@cjbarth 

1. Version 2.0.5 and 2.1.0, definitely typed pkg removed. Gives the error of incompatible req type because we are extending express request with custom fields, as well as it is done in the passport-saml.
Please see screenshots below:

![image](https://user-images.githubusercontent.com/32565392/113932527-652e0680-97fc-11eb-9412-0377595a643a.png)
![image](https://user-images.githubusercontent.com/32565392/113932552-6a8b5100-97fc-11eb-8a66-b268e004ba71.png)

2. I have tried to install pkg from master branch, but the error still persists.

**Comment by Mikescops** [comment]
I think the fix #554 by @forty solves this issue but it should be backported to 2.x

**Comment by cjbarth** [comment]
v3 of `passport-saml` has been released. If there is a PR to backport #554 to 2.x, we'll look at it there.
