### ISSUE TITLE
[BUG] Possibility to overwrite profile fields with data from attributes

### ISSUE THREAD

**Issue by gtokarz** [node-saml/passport-saml#543]
Currently attributes are mapped to profile without any check, which might at best cause minor issues with previously present properties from profile object.

**To Reproduce**

Configure Idp/craft a SAML response with attribute Name set to i.e issuer or other profile field set before attribute mapping. Mapped profile object should now have overwritten issuer field.

**Expected behavior**
It should check if property already exists on the profile object and only map values when key is not present.
https://github.com/node-saml/passport-saml/blob/f1a436fa243080f8cfcf06fd0f40ce3af396c8b6/src/passport-saml/saml.ts#L1319

**Environment**

- Node.js version: 12.16.1
- passport-saml version: 2.0.5

**Comment by cjbarth** [comment]
@gtokarz would you be willing to create a PR with tests for this?

**Comment by gtokarz** [comment]
@cjbarth Yes, I might have some time on Monday to do so

**Comment by cjbarth** [comment]
@gtokarz We are preparing a 3.0 release. Would you be interested in getting this change up for PR in the next few weeks to make it in to 3.x?

**Comment by kriss1897** [comment]
@cjbarth @gtokarz Is it okay if I raise a PR for this?

**Comment by cjbarth** [comment]
@kriss1897 sure, anything with a `pr-welcome` tag we are happy to have someone help with. Please make sure to include tests for this.

**Comment by gtokarz** [comment]
yes, go ahead with PR

**Comment by kriss1897** [comment]
@cjbarth @gtokarz I've raised a PR for fixing this, however I'm unable to assign any reviewers. Please take a took when you guys have time.
