### ISSUE TITLE
[BUG] TypeScript Strategy is incompatible with Passport Strategy

### ISSUE THREAD

**Issue by fluggo** [node-saml/passport-saml#549]
Small bug: When using the types from the latest passport-saml, a new Strategy object can't be used in a passport.use() call.

**To Reproduce**

```typescript
passport.use(new passportSaml.Strategy({} as any, (profile: any, done: passportSaml.VerifiedCallback) => {
  done(null, profile, {});
});
```

**Expected behavior**
The docs suggest this very usage, so it should pass TypeScript checks without errors. Unfortunately, the strategy's authenticate() method requires a [samlLogoutRequest](https://github.com/node-saml/passport-saml/blob/master/src/passport-saml/types.ts#L146) property to appear on the request object, and since express doesn't provide that, it fails.

**Environment**

- Node.js version: 14.15.4
- TypeScript version: 4.1.5
- passport-saml version: 2.0.5

**Comment by cjbarth** [comment]
@fluggo What docs suggest this? I'm not sure what you're trying to accomplish here. Also, it seems you're missing a `)`, as there aren't enough, so the syntax isn't correct. Sorry if I'm missing something obvious.

**Comment by fluggo** [comment]
Ah, you're right about the parentheses. Sorry, I was in a hurry, and was adapting my code. Let's try with a complete TypeScript file, this time directly from the main readme:

```typescript
import * as passport from 'passport';
import { Strategy as SamlStrategy } from 'passport-saml';

passport.use(new SamlStrategy(
  {
    path: '/login/callback',
    entryPoint: 'https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php',
    issuer: 'passport-saml'
  },
  function(profile, done) {
    findByEmail(profile.email, function(err, user) {
      if (err) {
        return done(err);
      }
      return done(null, user);
    });
  })
);
```

TypeScript gives this error:

![image](https://user-images.githubusercontent.com/2552507/110062335-b135e900-7d2e-11eb-9f4d-9333d0d314e9.png)

**Comment by cjbarth** [comment]
@fluggo I still can't seem to duplicate this problem. I've checked out `passport-saml` at `v2.0.5` and `npm install --save-dev @types/passport@1.0.6` and then put the following code in `passport-saml/src/test.ts` with the following code:

```js
import * as passport from "passport";
import { Strategy as SamlStrategy } from "./passport-saml";
import { Profile, VerifiedCallback } from "./passport-saml/types";

function findByEmail(email: string, cb: VerifiedCallback) {
  cb(null);
}

passport.use(
  new SamlStrategy(
    {
      path: "/login/callback",
      entryPoint:
        "https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php",
      issuer: "passport-saml",
    },
    function (profile: Profile | null | undefined, done: VerifiedCallback) {
      if (profile != null && typeof profile.email === "string") {
        findByEmail(profile.email, function (err, user) {
          if (err) {
            return done(err);
          }
          return done(null, user);
        });
      }
    }
  )
);
```

**Comment by fluggo** [comment]
Hmm. I can't explain it. I have one project where this fails, and a fresh project where this succeeds. I haven't yet figured out what the difference is between the two. I'll have to get back to you.

**Comment by fluggo** [comment]
Okay, this *has* to be a bug in TypeScript. Check this out:

```typescript
interface A { thing: string; }
interface B { stuff: string; thing: string; }

interface C {
  authenticate(req: A): void;
}

const dd = {
  authenticate(req: B): void {
    console.log(req.stuff.toLowerCase());
  }
}

const cc: C = dd;

cc.authenticate({thing: 'happy'});

interface E {
  (req: A): void;
}

type F = C["authenticate"];
type G = (req: A) => void;

const ee: E = (req: B) => 0;
const ff: F = (req: B) => 0;
const gg: G = (req: B) => 0;
```

TypeScript should be calling out errors on the assignments to cc, ee, ff, and gg because B is not assignable to A, but it's only seeing errors on the assignments to ee and gg. This program crashes, by the way, because dd.authenticate() receives an object that's the wrong shape.

**Comment by fluggo** [comment]
One deep dive later, and I think I'm a little closer to understanding what's going on here—not exactly, but the above assignability behavior comes from strictFunctionTypes, which has the [caveat](https://github.com/microsoft/TypeScript/pull/18654) that function arguments (including functions as object properties) are considered contravariant under this flag, but method arguments are considered bivariant. Under bivariance, the passport-saml types should work. Under contravariance, they should not.

In other words, this passes under strictFunctionTypes:

```typescript
interface A { thing: string; }
interface B { stuff: string; thing: string; }

interface C {
  authenticate(req: A): void;
}

const dd = {
  authenticate(req: B): void {
    console.log(req.stuff.toLowerCase());
  }
}

const cc: C = dd;
```

This does not:

```typescript
interface A { thing: string; }
interface B { stuff: string; thing: string; }

interface C {
  authenticate: (req: A): void;
}

const dd = {
  authenticate(req: B): void {
    console.log(req.stuff.toLowerCase());
  }
}

const cc: C = dd;
```

Now the mystery that's left—what about our code is making TypeScript see one situation one way, and the other a different way?

**Comment by cjbarth** [comment]
A significant refactor has taken place for the 3.0.0 release. If this issue persists in that release, please reopen this issue.

**Comment by bvds** [comment]
I am seeing the exact same error with passport@0.6.0 and passport-saml@3.2.4
![Screenshot from 2022-11-09 11-12-57](https://user-images.githubusercontent.com/45844/200908873-5e7b4d04-7fad-4066-a030-86f48d0e17f0.png)

**Comment by bvds** [comment]
Also, the two examples in the post above https://github.com/node-saml/passport-saml/issues/549#issuecomment-814579568 appear to be identical.  Am I missing something?

**Comment by jbinto** [comment]
We're starting to see this after upgrading from `passport-saml@3.2.4` to `@node-saml/passport-saml@4.0.1`. `passport@0.6.0` remained unchanged. 

I've spent a long time debugging so I have lots of theories but also a lot of dead ends, so I don't want to muddy the waters too much. 

[A comment in #678 points out](https://github.com/node-saml/passport-saml/pull/678#issuecomment-1084969357) that this only seems to happen when your application "patches" express.User. That is the case for us.

**Comment by fluggo** [comment]
> Also, the two examples in the post above [#549 (comment)](https://github.com/node-saml/passport-saml/issues/549#issuecomment-814579568) appear to be identical. Am I missing something?

Yes. Look closely at the `interface C` declaration.

**Comment by cjbarth** [comment]
> We're starting to see this after upgrading from `passport-saml@3.2.4` to `@node-saml/passport-saml@4.0.1`. `passport@0.6.0` remained unchanged.

Since so much has changed since this bug was opened, let's create a new one instead of reopening this one. I still haven't seen problems with the types, but that doesn't mean there aren't any.
