### ISSUE TITLE
[BUG] It keeps saying this error when theres nothing wrong could you help me?

### ISSUE THREAD

**Issue by LilElviss** [node-saml/passport-saml#621]
It keeps saying this error: Error: Cannot find module 'C:\Users\sofia\Documents\DiscordBot\main.1s'. Please verify that the package.json has a valid "main" entry
←[90m    at tryPackage (internal/modules/cjs/loader.js:321:19)←[39m
←[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)←[39m
←[90m    at resolveMainPath (internal/modules/run_main.js:16:25)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:70:24)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  path: ←[32m'C:\\Users\\sofia\\Documents\\DiscordBot\\package.json'←[39m,
  requestPath: ←[32m'C:\\Users\\sofia\\Documents\\DiscordBot'←[39m
}

**Comment by cjbarth** [comment]
I'm sorry you are getting errors. Unfortunately, there isn't enough information here for anyone to help you.
