### ISSUE TITLE
Error: Invalid signature from encrypted assertion

### ISSUE THREAD

**Issue by aw1875** [node-saml/passport-saml#627]
Hi there! I had another issue stemming from the [key encryption algorithm](https://github.com/node-saml/passport-saml/issues/618) not being supported a little while back which has now been solved by my IdP. Now it seems that after a successful login I am redirected back correctly but presented with this error:

```
Error: Invalid signature from encrypted assertion
    at SAML.validatePostResponseAsync (/var/www/shibb/node_modules/passport-saml/lib/node-saml/saml.js:598:27)
```
    
I believe this is related to my cert and key (correct me if I'm wrong please) but I'm not 100% sure so wanted to find out.

Thanks!

**Comment by cjbarth** [comment]
There isn't much to go on here, so this isn't really a bug. I'll make this a discussion so more dialog can be had there.
