### ISSUE TITLE
[BUG] Vulnerability dependency library xmldom 

### ISSUE THREAD

**Issue by TTmaister** [node-saml/passport-saml#628]
I noticed that xmldom library <0.7.0 on vulnerability.
https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q

**Comment by forty** [comment]
See https://github.com/xmldom/xmldom/issues/271

I don't know what others thinks, but my intuition is that since it impacts serialization rather than parsing, it should not be too bad for passport SAML.

I'm not sure if if worth somehow vendoring the dependency in the meantime.

**Comment by forty** [comment]
My bad, actually it could very well impact us, see https://mattermost.com/blog/securing-xml-implementations-across-the-web/

Not sure why but we are re-stringifying things before reparsing https://github.com/node-saml/passport-saml/blob/3.x/src/node-saml/saml.ts#L790

That doesn't seem like a good idea, though there might be good reasons why we would do that.

**Comment by TTmaister** [comment]
Sounds like a plan. Personally, I don't know the passport-saml node application so well that I could just go change the version number reference and try it in a private repository.

**Comment by shubham-bibliu** [comment]
New version 0.7.0 is available now [/@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom).
[xml-crypto](https://www.npmjs.com/package/xml-crypto) already [updated](https://github.com/yaronn/xml-crypto/blob/master/package.json#L13)

**Comment by forty** [comment]
We will have to wait for 0.7.2 (at least, if I did not miss something again ^^) as there are types issues currently.

Relevant PR is here https://github.com/xmldom/xmldom/pull/288. xmldom maintainer is very reactive and helpful, so it should be merged quickly.

**Comment by forty** [comment]
Note that xml-encryption hasn't updated yet, and it might very well never happen, given the activity on that repo.

PR is here https://github.com/auth0/node-xml-encryption/pull/88

**Comment by forty** [comment]
https://github.com/node-saml/node-saml/pull/17

**Comment by PCOffline** [comment]
Has this been resolved with v3.1.2? If so, let's close this issue

**Comment by markstos** [comment]
According to the Release notes for 3.1.2, yes.

https://github.com/node-saml/passport-saml/releases/tag/v3.1.2

**Comment by imsiddhants** [comment]
I'm on passport-saml v1.3.3 any ground breaking changes to upgrade to 3.1.2 or 3.2.4?
