### ISSUE TITLE
[BUG] Undocumented breaking change with the `protocol` config option when updating to v3

### ISSUE THREAD

**Issue by pablaber** [node-saml/passport-saml#677]
Just came across this and thought it would be good to bring up to prevent further issues. Although the documentation for v1 and v2 say that the `protocol` field defaults to `http://`. When looking at the code, it actually looks like the `protocol` field will default to the value of the current request, and not `http://`.

https://github.com/node-saml/passport-saml/blob/v1.1.0/lib/passport-saml/saml.js#L97-L99

We were previously not setting the `protocol` value when setting our passport SAML config, but once we updated to v3 the protocol will **actually** default to `http://` instead of what is on the request. This caused all of our callback URLs to start being sent as http://auth.domain.com/callback instead of https://auth.domain.com/callback without any code changes.

A quick note here that this seemed to not affect Okta and OneLogin SAML providers, as I _believe_ that they may just use the ACS URL that they store themselves and ignore the ACS URL sent with the SAML login request? Either that or they were forcing https regardless of the protocol of the ACS URL being sent in the request. We did see Issues with google and Shibboleth though.

**Comment by markstos** [comment]
How do you propose the docs for this are fixed? We use GitHub Releases and I don't think we can go back and edit the 3.0 release notes. Patch welcome.

**Comment by pablaber** [comment]
Good point, I think you can edit release notes in GitHub and just mention the breaking change there instead? Not sure that I'm able to do that on this repository.

**Comment by cjbarth** [comment]
We can add to the override file for GitHub Release Notes. I hope to have some time this week or next to get back to this project and I can help then if you don't figure it out before then.

**Comment by markstos** [comment]
I'm not sure to do this with `release-it`, but unless `release-it` would revert the change, we /can/ edit the release notes for historical releases. https://github.com/node-saml/passport-saml/releases/edit/v3.0.0

Since I'm usually do not working on releases lately, I'll wait till @cjbarth has some time to look at this.

**Comment by cjbarth** [comment]
The tool that generates release notes will re-generate `CHANGELOG.md`, so a PR to change that, will get modified the next time through. We can manage that through careful merging, but that gets complex over time. It would be better if we modified `.grenrc.js` to simply change the commit message of the commit that actually caused the break. That will fix it for all future runs of [GREN](https://github.com/github-tools/github-release-notes). However, modifying the release notes in GitHub Releases manually would be a good, safe, first step.

**Comment by cjbarth** [comment]
@pablaber I'm not sure where I see a deliberate change from `http` to `https`. It looks like we are building `http` by default as before. Though I think we should probably switch to `https` for the v4 release. Can you please comment further?

https://github.com/node-saml/passport-saml/blob/6ba76ba3a015fea96a2dd38f661a6c1f85bc44a1/src/node-saml/saml.ts#L184-L201

**Comment by pablaber** [comment]
This was from a while ago so not totally fresh in my mind, but I believe the main issue was just that the docs for v1/v2 mentioned `http` as the default protocol, but based off the code snippet I linked from v1.1.0:

https://github.com/node-saml/passport-saml/blob/v1.1.0/lib/passport-saml/saml.js#L97-L99

It shows that the protocol was actually defaulting to `req.protocol` before it defaulted to `http` (which I believe is what caused me some problems until I dug in and figured that out). 

Because of this, we were originally not bothering to set `options.protocol` when we were using v1, and then when attempting to update to `v3` the `protocol` field was defaulting to `http` as documented but we hadn't made any code changes besides the version bump. 

Regardless, I think switching to `https` is a good idea for v4 as well.
