### ISSUE TITLE
[BUG] options.authnContext as a string is no longer supported

### ISSUE THREAD

**Issue by innovatechs** [node-saml/passport-saml#681]
Hi everyone

We have defined the options.authnContext parameter as a string (client configuration) and we are getting an error because the new versions of Passport-SAML are expecting this parameter to be an array only. This is a regression compared to previous versions which support both string and array types.

**Expected behavior**

The previous versions were creating an array which contains options.authnContext string item.

**Environment**

- Node.js version: 14
- `passport-saml` version: 3.2.1

**Comment by srd90** [comment]
I believe that this was discussed at PR #615 (see especially comment https://github.com/node-saml/passport-saml/pull/615#issuecomment-867818849)
