### ISSUE TITLE
[BUG] Error: req#logout requires a callback function with passport@^0.6.0

### ISSUE THREAD

**Issue by sebsauer90** [node-saml/passport-saml#768]
Hello, first thanks for this package :) 
So, now the problem:

We've updated passport to 0.6.0 and now we get the following error:
`Error: req#logout requires a callback function`

This is because passport now requires a logout callback function, as you can see here:
[https://www.passportjs.org/concepts/authentication/logout/](https://www.passportjs.org/concepts/authentication/logout/)

In the `validateCallback` function in the `authenticate` method of the `AbstractStrategy` class you are using `req.logout()` without a callback function.

Is it possible to make an update for this? :)

Thanks a lot!
Seb

**Comment by sebsauer90** [comment]
Is here a maintainer, who can say if we can expect an update soon? :)

**Comment by sebsauer90** [comment]
Hey @cjbarth,
we are using **passport-saml**@3.2.1 and want to update **passport**@0.5.2 to 0.0.6.
So we are not using an 0.x version of passport-saml :P
Thanks a lot for your answer, then we will try the beta version I think :)

**Comment by cjbarth** [comment]
The final release of 4.0.0 was released.
