### ISSUE TITLE
[BUG] Prototype Pollution vulnerability in @xmldom/xmldom@0.7.5

### ISSUE THREAD

**Issue by BenBullock1992** [node-saml/passport-saml#789]
Hello,

Snyk identified a Prototype Pollution vulnerability in @xmldom/xmldom@0.7.5 which is a dependency of passport-saml@3.2.2.

https://security.snyk.io/vuln/SNYK-JS-XMLDOMXMLDOM-3042243

Please could you update @xmldom/xmldom to 0.8.3.

Thanks,

Ben

**Comment by jftanner** [comment]
It looks like it's [not a direct dependency](https://github.com/node-saml/passport-saml/blob/master/package.json).

Rather, it's a direct dependency of [node-saml](https://github.com/node-saml/passport-saml/blob/master/package-lock.json#L566-L593) at v0.8.3, as well as its nested dependencies [xml-crypto and xml-encryption](https://github.com/node-saml/passport-saml/blob/master/package-lock.json#L8004-L8046) at v0.7.5.

**Comment by jftanner** [comment]
Digging in, it looks like [xml-crypto](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js) and [xml-encryption](https://github.com/auth0/node-xml-encryption/blob/e8df80cce4b0f1442fb14f526dc94b7a5bd0fe34/lib/xmlenc.js) packages only use the `DOMParser` constructor and instance `parseFromString` method.

_TBD if those are vulnerable._

**Comment by jftanner** [comment]
You're right @srd90. Helps if I read more thoroughly. Thanks for the correction.

Fortunately, the PR to backport the fix to `@xmldom/xmldom 0.7.x` will also apply to passport-saml, once released.

**Comment by cjbarth** [comment]
Unless there is a CVE published for a dependency that the 3.x series uses, we likely won't be updating it. Even then, we hope to have the 4.x series released in November, after which we won't update the 3.x series at all. For `master`, dependabot will help us with the dependencies and we try to stay up with that as you can tell from the commit history and changelog.

**Comment by abcd-ca** [comment]
@cjbarth Can this issue be re-opened? There is a CVE☝️.

**Comment by cjbarth** [comment]
Feel free to make a PR against the 3.x branch. 4.0.1 is already released with the fix.
