### ISSUE TITLE
Readme is wrong

### ISSUE THREAD

**Issue by MickL** [node-saml/passport-saml#809]
The readme shows the following example:

```
passport.use(
  new MultiSamlStrategy(
    {
      passReqToCallback: true, // makes req available in callback
      getSamlOptions: function (request, done) {
        findProvider(request, function (err, provider) {
          if (err) {
            return done(err);
          }
          return done(null, provider.configuration);
        });
      },
    },
    function (req, profile, done) {
      // for signon
      findByEmail(profile.email, function (err, user) {
        if (err) {
          return done(err);
        }
        return done(null, user);
      });
    },
    function (req, profile, done) {
      // for logout
      findByNameID(profile.nameID, function (err, user) {
        if (err) {
          return done(err);
        }
        return done(null, user);
      });
    }
  )
);
```

But this doesnt seem to be valid JavaScript. All three parameter contain a function within a function:

```
function (request, done) {
            findProvider(request, function (err, provider) {
```

Further the example shows `new SamlStrategy()` and `new MultiSamlStrategy()` with three arguments but according to the TypeScript interface the constructor only accepts two arguments. In this case I wonder if the Typings are wrong or the readme.

<img width="650" alt="Bildschirm­foto 2022-11-10 um 16 11 50" src="https://user-images.githubusercontent.com/5103210/201132478-14b46490-28de-4aa9-a888-18b0b173ebeb.png">

**Comment by cjbarth** [comment]
Where are you seeing this problem? This is the code I see in `master`:

https://github.com/node-saml/passport-saml/blob/0a0e80c1448283c915ccc4550e139f16f52f828d/src/multiSamlStrategy.ts#L12-L27

**Comment by MickL** [comment]
Sorry I have installed `passport-saml` instead of `@node-saml/passport-saml` because this is what the Readme told me to do:

https://github.com/node-saml/passport-saml/blob/master/README.md

**Comment by MickL** [comment]
This has been copied from the readme:

```
passport.use(
  new SamlStrategy(
    {
      path: "/login/callback",
      entryPoint:
        "https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php",
      issuer: "passport-saml",
      cert: "fake cert", // cert must be provided
    },
    function (profile, done) {
      // for signon
      findByEmail(profile.email, function (err, user) {
        if (err) {
          return done(err);
        }
        return done(null, user);
      });
    },
    function (profile, done) {
      // for logout
      findByNameID(profile.nameID, function (err, user) {
        if (err) {
          return done(err);
        }
        return done(null, user);
      });
    }
  )
);
```

I just want to point out the point that doesnt seem to be valid code to me:
```
function (profile, done) {
      // for logout
      findByNameID(profile.nameID, function (err, user) {
        if (err) {
          return done(err);
        }
        return done(null, user);
      });
    }
```

Maybe you meant to exectue a already defined function `findByNameID` which takes nameID AND another function into it. Very confusing IMO, personally I would make the example more simple or just add comments would make it more clear to me:

```
passport.use(
  new SamlStrategy(
    {
      path: "/login/callback",
      entryPoint:
        "https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php",
      issuer: "passport-saml",
      cert: "fake cert", // cert must be provided
    },
    function (profile, done) {
      // for signon
    },
    function (profile, done) {
      // for logout
    }
  )
);
```

**Comment by cjbarth** [comment]
I see what you are saying now. I'll have a look and put up a PR with something clearer.

**Comment by MickL** [comment]
I put up a PR, maybe you like it :)

**Comment by cjbarth** [comment]
@MickL , perhaps the changes I've made to the README [here](https://github.com/node-saml/passport-saml/pull/812) will help clear things up.

If so, feel free to close this and #811.

**Comment by cjbarth** [comment]
The code you propose in #811 returns a variable that isn't in scope, `user`, which makes it invalid JS. This proposal adds information explaining how it is supposed to work. Basically, you just have to implement those functions yourself and call the callback in the standard [Node-back](https://nodejs.org/en/knowledge/errors/what-are-the-error-conventions/) pattern.

> I was thinking node-saml can be used without passport and passport-saml is just a wrapper to make it work with passport.

This is entirely true, and I think we have a lot of README updates to make this clear. Feel free to offer suggestions along these lines.

**Comment by MickL** [comment]
Yes the `// ...` means "implement your own code". Using named functions that also require another function to put in makes it super confusing IMO. I will close everything tho as you dont like it.

**Comment by cjbarth** [comment]
I see that; so one type of unclear which isn't syntactically valid vs. another type of unclear that references unseen code; pick your poison I guess 🤷‍♂️
