### ISSUE TITLE
[BUG] Passport SAML is always chosen first by NestJS Passport, no matter the order

### ISSUE THREAD

**Issue by PaulSchult** [node-saml/passport-saml#828]
When using NestJS and Passport to authenticate users, SAML will always be chosen as the first method. I'm providing the Passport several strategies as a fallback, but if SAML is somewhere in that array it will always be the first to check.

**To Reproduce**
Steps to reproduce the behavior. Ideally, expressesd through an automated test.

1. Use NestJS and Passport for authentication
2. Create SAML Strategy
3. Provide passport basic and saml as a strategy
4. Start the authentication process
5. Notice that you will be redirected to SAML accessUrl

**Expected behavior**
I expect that Passport would try to use all other strategies in front of SAML before using SAML itself.

**Environment**

- Node.js version: 18.10.0
- `passport-saml` version: 3.2.1

**Comment by cjbarth** [comment]
This is either a problem with your code, or a problem with Passport. By the time that any code is executing in `passport-saml`, the decision has already been made as to which authentication provider will be used.

Also, please note that the 3.x series of `passport-saml` is now deprecated.
