### ISSUE TITLE
Cannot POST /saml/consume

### ISSUE THREAD

**Issue by smclinden** [node-saml/passport-saml#847]
Apologies, in advance, for reporting this as a BUG since I don't think that it is an issue with passport-saml  so much as it is for the code using it and I was hoping to get some advice on where to look to fix it. I tried the Discussions section but even logged in I could not start a new discussion.

Feel free to delete/close this if you feel that it is inappropriate.

I am running I GraphQL application that uses passport for authentication. It has gone through major revisions in terms of dependencies but it is using a deprecated version of passport-saml. The callback URL is:

```
https://www.site.org:4000/saml/consume
```
And this has worked for a few years. But after upgrading, with no change in configuration  (but changes to the Python and Node dependencies), I get the error, above. The last version that worked also used passport-saml 3.2.4 so there has been no change, here.

What I am really looking for is a place to start.

**Environment**

- Node.js version:18.13.0
- passport-saml` version: 3.2.4
- Yarn version: 3.2.0
- Ubuntu version: 20.04

**Comment by markstos** [comment]
@srd90 Thanks for the triage. It sounds like this can be closed then?
