### ISSUE TITLE
[BUG] Importing @node-saml/passport-saml gives type error

### ISSUE THREAD

**Issue by lcundiff** [node-saml/passport-saml#882]
When importing @node-saml/passport-saml, Typescript gives the following error: 
`namespace 'servestatic' has no exported member 'requesthandlerconstructor'.`

I have made sure to install all dependencies and am using the newest versions of all package dependencies including Express.

**To Reproduce**
1. npm i @node-saml/passport-saml
2. add `import { Strategy } from "@node-saml/passport-saml"` to your code

**Expected behavior**
Should run without type error. 

**Environment**
- Node: 14
- passport-saml: 4.0.4 (latest)
- typescript : ^4.4.3
- expression: 4.17.1
- @types/express: "^4.17.3

**Comment by lcundiff** [comment]
@srd90 Thank you for looking into this and apologies for not attaching package.json and other code. I was using the example code, so it is the same as you have in your example there. However, I had tested the error when erasing all of my code and only including the import statement, and the error still existed, so it is not due to the implementation. 

Did you have typescript installed? I will add that to the environment above to be more explicit with Typescript being required for the error to occur. 

I will look into the DefinitelyTyped issue and see if that resolves it and follow up here either way in a couple of days. Thank you again.

**Comment by cjbarth** [comment]
@lcundiff , did you have any followup on this? If so, please let us know and we can reopen.
